version = 0.1
default-task = 'start'

[[task]]
name = 'start'
env = { TZ='UTC', NODE_ENV='development'}
deps = [ "prettier"]
run = """
node \
  --trace-warnings \
  src \
    --volume /home/zach/somisana-data \
    --key TjWnZr4u7w!z%C*F-JaNdRgUkXp2s5v8 \
    --login localhost
"""

[[task]]
name = 'prettier'
deps = [ 'src/**/*.js' ]
run = """
prettier \
  --loglevel warn \
  --cache \
  --cache-strategy metadata \
  --ignore-path .prettierignore \
  --write "src/**/*.@(js|json|yml)" \
  --write "./.github/**/*.@(js|json|yml)" \
  --write "./deploy/**/*.@(js|json|yml)" \
"""