version = 0.1
default-task = 'start'

extensions = ['./prettier.js']

[[task]]
name = 'start'
env = { TZ='UTC', NODE_ENV='development'}
deps = [ "prettier:server"]
run = """
node \
  --trace-warnings \
  src \
    --volume /home/zach/somisana-data \
    --key TjWnZr4u7w!z%C*F-JaNdRgUkXp2s5v8 \
    --login localhost
"""

[[task]]
name = 'prettier'
watch-invalidation = 'skip-running'
deps = ['prettier:other', 'prettier:server']

[[task]]
name = 'prettier:server'
deps = [ 'src/**/*.js' ]
template = 'prettier'
[task.template-options]
ignore-path = '.prettierignore'
files = 'src/**/*.@(js|json|yml)'
log-level = 'log'



# [[task]]
# name = 'prettier:server'
# deps = [ 'src/**/*.js' ]
# watch-invalidation = 'skip-running'
# run = """
# prettier \
#   --write "src/**/*.@(js|json|yml)"
# """

[[task]]
name = 'prettier:other'
run = """
prettier \
  --loglevel warn \
  --cache \
  --cache-strategy metadata \
  --ignore-path .prettierignore \
  --write "./*.@(js|json|yml|md)" \
  --write "./.github/**/*.@(js|json|yml)" \
  --write "./deploy/**/*.@(js|json|yml)" \
"""