version = 0.1
default-task = 'start'

extensions = ['./prettier.js']

[[task]]
name = 'start'
env = { TZ='UTC', NODE_ENV='development'}
deps = [ "prettier:server"]
run = """
node \
  --trace-warnings \
  src \
    --volume /home/zach/somisana-data \
    --key TjWnZr4u7w!z%C*F-JaNdRgUkXp2s5v8 \
    --login localhost
"""

[[task]]
name = 'prettier'
deps = ['prettier:other', 'prettier:server']

[[task]]
name = 'prettier:server'
deps = [ 'src/**/*.js' ]
template = 'prettier'
[task.template-options]
ignore-path = '.prettierignore'
files = 'src/**/*.@(js|json|yml)'
loglevel = 'warn'
config = '.prettierrc'

[[task]]
name = 'prettier:other'
template = 'prettier'
[task.template-options]
ignore-path = '.prettierignore'
files = './*.@(js|json|yml|md) ./.github/**/*.@(js|json|yml) ./deploy/**/*.@(js|json|yml)'
loglevel = 'warn'
config = '.prettierrc'