version: '3.8'

networks:
  mnemosyne_stable:
    name: mnemosyne_stable
    driver: overlay
    attachable: true

services:
  public-nginx:
    image: $NGINX_IMAGE
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
    ports:
      - 7010:80
    networks:
      - mnemosyne_stable

  private-nginx:
    image: $NGINX_IMAGE
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
    ports:
      - 6008:80
    networks:
      - mnemosyne_stable

  private-node:
    image: $DOCKER_IMAGE
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
    environment:
      ALLOWED_ORIGINS: '*'
    volumes:
      - /opt/mnemosyne:/mnemosyne
    networks:
      - mnemosyne_stable

  public-node:
    image: $DOCKER_IMAGE
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
    environment:
      ALLOWED_ORIGINS: '*'
    volumes:
      - /opt/mnemosyne:/mnemosyne
    networks:
      - mnemosyne_stable
